name: hotkey_manager
description: This plugin allows Flutter desktop apps to defines system/inapp wide hotkey (i.e. shortcut).
version: 0.2.0
homepage: https://github.com/leanflutter/hotkey_manager

platforms:
  linux:
  macos:
  windows:

topics:
  - hotkey
  - shortcuts
  - global-hotkey
  - global-shortcuts

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  uuid: ">=3.0.7 <5.0.0"

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: HotkeyManagerPlugin
      macos:
        pluginClass: HotkeyManagerPlugin
      windows:
        pluginClass: HotkeyManagerPlugin
